name: BukkitTubeExample
description: Watch videos
author: Mitch528
depend: [ProtocolLib, BukkitTube]
main: org.mitch528.BukkitTube.example.Example
version: 1.0
commands:
   loadvideo:
      description: Load a video onto a map.
      usage: /loadvideo [file name]
      permission: btube.loadvideo
   replay:
      description: Replay a video
      usage: /replay
      permission: btube.replayvideo