name: BukkitTube
version: 0.0.1
description: Watch videos
author: Mitch528
depend: [ProtocolLib]
main: org.mitch528.BukkitTube.BukkitTube
commands:
   loadvideo:
      description: Load a video onto a map.
      usage: /loadvideo [file name]
      permission: btube.loadvideo
   replay:
      description: Replay a video
      usage: /replay
      permission: btube.replayvideo